### ISSUE TITLE
Archive empty

### ISSUE THREAD

**Issue by shawnyeager** [cdevroe/cypress-microblog#11]
First, thanks, @cdevroe, for this theme. It's great. 

I made the switch last night, and all looks well, except that I'm seeing an empty body at `/archive/`. 

Here it is: [https://yeager.wtf/archive/](https://yeager.wtf/archive/). 

Anyone else having this problem?

**Comment by shawnyeager** [comment]
And I just realized that `/photos/` is also failing to generate.

**Comment by cdevroe** [comment]
@shawnyeager Sorry that you're having this issue. And also thanks for your patience. I will have to check with @manton on why this might be happening specifically for you. Perhaps it is a Cypress issue that we can fix.

**Comment by svendahlstrand** [comment]
This problem, and a tempory workaround, is also mentioned in [Litany of errors on my blog](https://help.micro.blog/t/litany-of-errors-on-my-blog/767) at the Micro.blog Help Center.

**Comment by manton** [comment]
Thanks @svendahlstrand! I'm looking into this again today.

**Comment by manton** [comment]
I've been testing this and submitted a pull request #13.

**Comment by shawnyeager** [comment]
Thanks, @manton. Does this automatically get pulled into the micro.blog theme archive, or do I still need to clone?

**Comment by manton** [comment]
@shawnyeager Yes, we'll pull it in (probably today) if you're using the version of Cypress that's on the Design page. If you installed it as a plug-in, I'm also going to add Cypress to the plug-ins list so it can be updated there more easily.
