### ISSUE TITLE
Feature request: better spacing of multiple photos

### ISSUE THREAD

**Issue by shawnyeager** [cdevroe/cypress-microblog#12]
Would be great, I think, to have a bit of breathing room and maybe better alignment between multiple photos on post pages, as well as `/home/`, `/archive/`, etc.

An example: https://shawnyeager.org/2021/04/11/a-weekend-visit.html

**Comment by cdevroe** [comment]
@shawnyeager Thank you for the example. It appears as though all of the images are stacked within a single P tag. @manton  - Is this how Micro.blog always inserts images into a post? I would think if multiple images were added they'd be within their own paragraphs - or - wrapped differently altogether?

If this is typical behavior I can style against it and just add some margin around IMGs.

**Comment by manton** [comment]
Yep, the official apps just use a series of `img` tags for multi-photo posts.
