### ISSUE TITLE
Profile pic rendering

### ISSUE THREAD

**Issue by shawnyeager** [cdevroe/cypress-microblog#15]
I'm not sure if this is controlled/controllable via theme or a micro.blog issue, but the profile pic renders at dimensions which lead to heavy pixelation on mobile.

**Comment by shawnyeager** [comment]
cc: @manton

**Comment by manton** [comment]
I think it's using the default profile photo which is 200x200. It would look better if displayed at half that size. If you want to try that change, you could add this under Design → Edit CSS:

```
.logo img {
  width: 100px;
  height: 100px;
}
```

**Comment by cdevroe** [comment]
@shawnyeager @manton Do you recommend I patch Cypress to load the profile image smaller? Is there an option in Micro.blog somehow to have an alternate image in this spot? I could make it a config variable but that seems like it would be too difficult for many Micro.blog users.

**Comment by shawnyeager** [comment]
Thanks, @cdevroe. I'll defer to @manton on this.

**Comment by manton** [comment]
My 2 cents, I think it looks pretty good at half the full size like in the CSS I included below. Kind of a personal preference, I guess, so up to you @cdevroe what the default should be.

Once we finish moving themes to plug-ins, plug-ins have the option for a "settings" screen that makes it much more user-friendly to configure these kind of things if you want to make it an option in the future.

**Comment by cdevroe** [comment]
@manton Fire when ready. Merged a few fixes into 2022.1.1.
