### ISSUE TITLE
Responsive layout delayed due to document never being ready

### ISSUE THREAD

**Issue by jakel1828** [cdevroe/cypress-microblog#2]
The audio play button covers some of the text on mobile (iPhone 7). micro.blog defaults to putting the audio player at the end, but I think it's more user friendly having it at the beginning, which causes the issue.

![](http://jakelacaze.com/uploads/2021/9542903e53.jpg)

It looks fine when I zoom in a bit.

![](http://jakelacaze.com/uploads/2021/87a7e00487.jpg)

**Comment by cdevroe** [comment]
@jakel1828 Thank you for reporting an issue! I appreciate the screenshots as well. That helps a lot.

It appears as though the mobile view isn't loading at all on some Micro.blogs - perhaps due to the number of posts being loaded before the script fires. I'll be taking a close look at this because it affects many sites.

**Comment by cdevroe** [comment]
@jakel1828 I'm made an attempt at a fix for this. I'm no longer seeing the issue in the next build. Lets see if it works for you before we close this issue.

**Comment by jakel1828** [comment]
It looks the same on my end. I had the same problem when I also tried on Chrome and Firefox.

**Comment by cdevroe** [comment]
@jakel1828 Yes, sorry Jake. The latest version hasn't been deployed to Micro.blog yet. That isn't something I'm able to do. Hopefully the team there will release the latest version soon!

**Comment by jakel1828** [comment]
I'm ignorant of how these things work, so I misunderstood. Thanks!

**Comment by cdevroe** [comment]
I'm reopening this issue because it appears that Cypress on Micro.blog has a wider viewport, which causes the media queries to not kick in. I'm trying to get to the bottom of it.

**Comment by cdevroe** [comment]
Got to the bottom of it. 2021.1.3 will be released on Micro.blog very soon and will fix this issue. Thanks to all for their patience. @jakel1828
