### ISSUE TITLE
Emojis and Apostrophes are not rendering in blog posts

### ISSUE THREAD

**Issue by cheribaker** [cdevroe/cypress-microblog#3]
Example with missing emojis: https://hypertext.monster/2021/03/22/progress-on-the.html

Example with missing apostraphe: https://hypertext.monster/2021/03/23/this-espresso-is.html

Both posts were created in the micro.blog iOS app.

**Comment by cdevroe** [comment]
@cheribaker Thank you for the specific examples. That makes it much easier to figure out what the issue may be. I know that Micro.blog has an apostrophe replacement technique, perhaps that character is not available in the font I've chosen for Cypress. We'll get this fixed up.

**Comment by kokodev** [comment]
Hi, maybe as another data point… also Umlauts and other unicode characters like '…' seem to have an issue with the encoding. Published with the macOS app: https://hutaffe.blog/2021/03/24/querdenker-rubikon-und.html

**Comment by cdevroe** [comment]
@kokodev Thank you very much for reporting it. This will help.

**Comment by cdevroe** [comment]
@cheribaker @kokodev This will be fixed once the new release is pushed to Micro.blog! :)

**Comment by cheribaker** [comment]
It's fixed on my end! Thanks so much.
