### ISSUE TITLE
Navigation menu cut off on some pages that do not have scrolling

### ISSUE THREAD

**Issue by danielsale** [cdevroe/cypress-microblog#4]
On my end, the micro.blog page list is cut off after HOME in Chrome & Firefox (Windows 10) due to either them not being fitted or that part of the theme not being scrollable.

**Comment by cdevroe** [comment]
@danielsale Thank you for reporting the issue so that I can figure it out. Can you share a URL of the issue? Or a screenshot? Also, is this on your phone, computer, tablet?

**Comment by danielsale** [comment]
It's on my laptop, which is situated in landscape mode. I saw it when I applied it to my micro.blog, and when I look at your's, now. It looks fine on my tablet, but there's more room. I would provide a screenshot but it wouldn't reveal much, it looks perfect other than "Home" is the only page link I see (it's at the bottom of that part of the page) and it goes no further to reveal the other pages.

**Comment by cdevroe** [comment]
@danielsale Out of curiosity, do you use the Page Zoom feature in your browser?

**Comment by danielsale** [comment]
Not really, it's zoomed to 100% all the time, and it's then when I see the problem. I can zoom out and see the other pages, though!

**Comment by toddgrotenhuis** [comment]
If we're talking about the left-navigation menu, mine also cuts off. I can only see 6 "pages" links on the left, and I have more than that. Scrolling while over the left menu scrolls the main page, and doesn't allow you to see the rest of the navigation menu.

![image](https://user-images.githubusercontent.com/165077/112463408-91e01980-8d38-11eb-94b3-edbd8ef22c71.png)

**Comment by cdevroe** [comment]
@toddgrotenhuis @danielsale thank you again. Now that #2 is fixed I can begin working on this one.

**Comment by cdevroe** [comment]
A fix for this will be in the next release on Micro.blog.
