### ISSUE TITLE
Responsive, mobile menu duplicates with each click of hamburger menu

### ISSUE THREAD

**Issue by gregmooreme** [cdevroe/cypress-microblog#5]
After scrolling a Cypress site on either a mobile device or a mobile-sized desktop browser window, the mobile menu duplicates itself down the length of the viewport. Screenshots are attached below showing the error.

Error on desktop:
![Screen Shot 2021-03-25 at 8 44 04 AM](https://user-images.githubusercontent.com/66031043/112474661-4af92080-8d46-11eb-998a-54a2d2f8064a.png)

Error on mobile:
![IMG_6751](https://user-images.githubusercontent.com/66031043/112473944-5b5ccb80-8d45-11eb-8573-ad9a44ceeb27.PNG)

**Comment by cdevroe** [comment]
Ah! This is happening when you click the "hamburger" multiple times. Thanks for catching this. Easy fix for the next build.

**Comment by gregmooreme** [comment]
Right, sorry about my terminology. Clicking the hamburger on the initial page load correctly brings up a single menu. However if you dismiss the menu, scroll the site, and click the hamburger again, the menu is duplicated to fill the entire viewport.

**Comment by cdevroe** [comment]
@gregmooreme This will be fixed in the next release.
