### ISSUE TITLE
Header disappears on Archives page on mobile

### ISSUE THREAD

**Issue by jakel1828** [cdevroe/cypress-microblog#6]
See the screenshot below for a visual of the problem.

![296D8ABE-2400-46E3-AC10-F259984C812B](https://user-images.githubusercontent.com/66526477/112490281-3c623780-8d4d-11eb-90a5-7b64298fdc9b.jpeg)

Thanks

**Comment by cdevroe** [comment]
Thanks @jakel1828 ... The archive and search results pages need some love. Will be coming soon!

**Comment by cdevroe** [comment]
Coming in next version.
