### ISSUE TITLE
Mobile search formatting

### ISSUE THREAD

**Issue by jakel1828** [cdevroe/cypress-microblog#9]
On mobile, the search still aligns in a thin line to the right. I'm having the same problem with mobile Safari and Firefox. I've included a screenshot from the official demo.

![IMG_2168](https://user-images.githubusercontent.com/66526477/115024268-77a3e200-9e85-11eb-9fbc-c1d8fea07ba0.PNG)

**Comment by cdevroe** [comment]
Thanks for reporting this. I'll get to work on it.

**Comment by shawnyeager** [comment]
Any progress?

**Comment by cdevroe** [comment]
@shawnyeager @jakel1828 I believe I have a patch for this staged. I'm waiting for Micro.blog to refresh the theme so I can truly test it.

But this is just a patch. I do not like the way Cypress currently displays search results. I think I'd prefer to move them to their own page, similar to how Cypress for WordPress works. So once we squash this immediate need I think that will be the next thing I focus on.

Once I verify the patch works, I'll roll that into the code for a release and ask Manton to pull in the latest.
